### PR TITLE
Show presentation texts and dueBefore on the select-instance page

### PR DESCRIPTION
**Pull request by ivarne**
This builds on 
- https://github.com/Altinn/app-lib-dotnet/pull/179
- https://github.com/Altinn/app-lib-dotnet/pull/177

and exposes that information in the frontend. It is fully backwards compatible with older versions of nuget packages (but will only show the new columns on newer package versions).

TODO:
* Find a better header for `PresentationTexts` (I went with `Texts`)
* Fix mobile layout to only show the new columns when they have values.
* Fix mobile layout. It looks ugly.

Images:
image
image

## Verification

- Manual testing
  - [ ] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added
  - [ ] Cypress E2E test(s) have been added
  - [ ] No automatic tests are needed here
  - [ ] I want someone to help me make some tests
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been updated
  
  - [ ] No changes/updates needed
- Changes/additions to component properties
  - [ ] Changes are reflected in both `src/layout/layout.d.ts` and `layout.schema.v1.json`, and these are all backwards-compatible
  - [ ] No changes made
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [ ] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [ ] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board

### CODE REVIEW

**Comment by Febakke** [comment]
I do agree with the action point that the mobile view could be better. If there is room for doing changes to it I can look into a more readable design?

**Comment by ivarne** [comment]
I'm not sure. This view is very analogous to the "message box", but limited to just one app, so they should probably be looked at together. My tentative wish list (for functionality, I'm not a designer) would be something like.

* Display Last Changed and Last Edited By (always)
* If availible display PrestentationValues and DueDate (but don't make a huge visual clue that they are missing)
* Button to continue working on the app (if not ended)
* Optional (by app configuration) button to create a new instance with a copy of the data
   * This would kind of make more sense if we had tabs for active and archived instances. Obviously archived instances would link to the Receipt instead of the edit view.
* `New Instance` button is hidden (or disabled) if the current user isn't allowed to create a new instance.

There are reasons to think some of this belongs in the message box, but configurability and dynamic functionality is much easier when it's an app specific thing.

**Comment by Febakke** [comment]
> Button to continue working on the app (if not ended)

Could you elaborate on this?

> Optional (by app configuration) button to create a new instance with a copy of the data
> This would kind of make more sense if we had tabs for active and archived instances. Obviously archived instances would link to the Receipt instead of the edit view.

I see that we have an issue related to this here: #286 
To hide not relevant information for the user another way to solve this would be to give the user a choice from the start: 
- Start new instance
- Continuo 
- Or make a copy of earlier instance

That way we could focus on more simple views. But this is a more time consuming task.

As of design, we have done some work on the mobile view for the table for the design system. It is added to some parts of Altinn 3. Maybe it should be added here as well. Or am I way of @olemartinorg ?

Tables for small screens are not easy. If we would use the design from the design system it would look something like this. It is a little heavy on the left side when there is no radio button so we might need to do some spacing changes. And it takes more vertical space, but it is more readable then the one shown here. 
Skjermbilde 2023-02-06 kl  12 46 48

**Comment by olemartinorg** [comment]
> As of design, we have done some work on the mobile view for the table for the design system. It is added to some parts of Altinn 3. Maybe it should be added here as well. Or am I way of @olemartinorg ?

Nope, you're spot on! :wink: I'll create a separate issue to describe that change. See here: #897

**Comment by ivarne** [comment]
I'd probably use "Tabs" (eller "Fane") instead of a radio button to decide whether to show active or archived instances.

I'm aware of https://github.com/Altinn/app-frontend-react/issues/286, but as I understand it the plan there is to somehow integrate it with the inbox that is shared with altinn 2. I'm just raising it as an issue here, because it might be relevant as part of a bigger picture if we decide to do something more than "Just extending the current functionality".

>> Button to continue working on the app (if not ended)
>
>Could you elaborate on this?

Just the same "Fortsett her" button that we have today. If extend the view to also include instances where the process has finished, the button to continue obviously should not be shown for those instances.

**Comment by Febakke** [comment]
I wasent thinking of radiobuttons, I was more thinking of different flows based on the task of the user, keeping the GUI simple. Someone that is going to start an instance from scratch dont need to see already started and archived instances. But this is something we can look into 🙌

**Comment by ivarne** [comment]
I don't think there is any context to derive the current task of the user from when they access the root url of the app without any parameters indicating a choice made in the inbox or wherever the user found the link. So far I know 4 possibilities (not all relevant for every app).

1. Create a new instance
2. Continue on an existing instance with more steps left in the process
3. Create a new instance based on a copy of a previous instance
4. Show a stateless view of the app (some apps)

**Comment by Febakke** [comment]
This is maybe outside the scope of this PR, but I guess we lack design for handling more functionality on this "start" page? I can create an issue to start looking on some different possibilities based on your comments?

**Comment by ivarne** [comment]
I’m beginning to think I should just remove the mobile changes in this PR, remove header on presentationTexts, and say this PR is a strict improvement. Further work should be moved to an issue.

**Comment by olemartinorg** [comment]
Removing this PR from our sprint - but just let me know when it's ready for review again, and we'll include it in our planning. 😊

**Pull request closed without merging**
