### PR TITLE
fix: setting focus on main content when navigating between tasks. Hid…

### PR DESCRIPTION
**Pull request by mikaelrss**
## Description
This fixes the same issues we had on v3 when focusing main content on screen navigation. 
https://github.com/Altinn/app-frontend-react/pull/1843

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [x] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [x] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Comment by mikaelrss** [comment]
I am guessing that the errors in the Cypress tests are because of the new changes in the frontend-test app.

**Comment by olemartinorg** [comment]
Sorry, tests will probably be failing until #1877 is merged

**Comment by mikaelrss** [comment]
> Sorry, tests will probably be failing until #1877 is merged

Yeah, no worries :smile: I think this PR can be review as it stands now.

**Review by olemartinorg — APPROVED** [review]

**Comment by olemartinorg** [comment]
I tested this now, and it seems to behave the way we want in most cases:
1. When loading an existing instance from a URL, `body` has focus
2. When starting `ttd/frontend-test` (which uses the instance selector for the first page), `body` has focus

The main content has focus when:
- I'm already working in the instance (1) and go to any other page
- I'm starting a new instance from the instance selector (2)
- I'm continuing to work on an existing instance from the instance selector (2)

However, if I turn off the instance selector in `ttd/frontend-test` (or just use any other app without the instance selector I guess, but I didn't bother - I just removed `onEntry` from `applicationmetadata.json` temporarily) the page load into a newly created instance and automatically sets focus to the main content right away.

**Pull request merged**
