### PR TITLE
Uploading all files to CDN on release

### PR DESCRIPTION
**Pull request by olemartinorg**
## Description
This should add all files from the `dist` folder to CDN, not just the js/css file. The only obvious weakness is that it will not delete previous files no longer part of the `dist` folder.

## Related Issue(s)
- #429

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- ~~[ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)~~

### CODE REVIEW

**Comment by olemartinorg** [comment]
Converting to draft: There are outstanding issues I should be figuring out here first:
1. What to do about the `altinn-app-frontend.js.LICENSE.txt` file
2. Could we easily clean up removed files to avoid cluttering the major/minor versions?

**Comment by haakemon** [comment]
> Converting to draft: There are outstanding issues I should be figuring out here first:
> 
> 1. What to do about the `altinn-app-frontend.js.LICENSE.txt` file
> 2. Could we easily clean up removed files to avoid cluttering the major/minor versions?

I think the proposed solution looks like a good solution. I dont think theres any reason to not publish the entire dist folder? There may be other assets included later as well that will need to be deployed, and this will avoi similar issues like the leaflet issue in the future.

1. Shouldnt we just publish the license file as well?
2. Not sure I understood this question

**Comment by chrisnruud** [comment]
2. the action does a mkdir that seems to be unique for the current run anyway, so the dir should be clean?

**Comment by olemartinorg** [comment]
1. @haakemon Yes, I agree.
2. @haakemon Say you have `some.artifact.js` which is introduced in v3.15, but removed again in v3.16. In the previous code it would still be present in the folder when v3.16 is copied into the v3 folder. I tested out removing previous files now, and the git log looks clean (git correctly deduces that you wanted a `M` for existing files, not a `D` and `A`, if that makes sense)
@chrisnruud Yup, but we run `mkdir -p`, so it's just to make sure the folder existed if it didn't exist already - it won't empty the folder.

**Comment by haakemon** [comment]
Ah, I get it now. I didnt think about the fact that its actually checking out the CDN repo as well. Thanks for the clarification. The workaround you added seems like a good approach to me.

**Review by haakemon — APPROVED** [review]

**Pull request merged**
