### PR TITLE
List component: Fix validation messages

### PR DESCRIPTION
**Pull request by johlie**
## Description
Made error message only show once even if there is more datamodelbindings in the table and changed the error message to include the label to the table.

## Related Issue(s)

- closes #{issue number}

## Verification/QA

- Manual functionality testing
  - [ ] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [ ] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Changes/additions to component properties
  - [ ] Changes are reflected in both `src/layout/layout.d.ts` and `layout.schema.v1.json`, and these are all backwards-compatible
  - [ ] No changes made
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [ ] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [ ] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [ ] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Comment by bjosttveit** [comment]
I accidentally broke the cypress script for external PRs. It is fixed in main now so could you merge main into your branch so that the tests will run?

**Review by olemartinorg — APPROVED** [review]
This looks allright by me. We aim to extract all these component-specific things out from files such as `validation.ts` (work ongoing in #377), but we haven't gotten around to cleaning up `validation.ts` quite yet. In light of that, it would be lovely if you could extend the cypress test to simulate some validation errors and assert that the error message only appears once. 🙏 That way we'll quickly know that we didn't break this once we start cleaning up (as I've mentioned before, every functionality without automatic tests can't really be guaranteed, because we don't go through every merged PR and re-test them after every change - we just trust that our test suite is complete). Let me know if you want some pointers on using `intercept()` in Cypress to make such a test!

**Comment by johlie** [comment]
> This looks allright by me. We aim to extract all these component-specific things out from files such as `validation.ts` (work ongoing in #377), but we haven't gotten around to cleaning up `validation.ts` quite yet. In light of that, it would be lovely if you could extend the cypress test to simulate some validation errors and assert that the error message only appears once. 🙏 That way we'll quickly know that we didn't break this once we start cleaning up (as I've mentioned before, every functionality without automatic tests can't really be guaranteed, because we don't go through every merged PR and re-test them after every change - we just trust that our test suite is complete). Let me know if you want some pointers on using `intercept()` in Cypress to make such a test!

Hi, yes we can try to make some tests. Would be nice with some pointers on using intercept().

**Comment by olemartinorg** [comment]
@johlie Sorry about this late reply! Here, I made an example test for you:

```typescript
  it('Validation messages should only show up once', () => {
    cy.goto('datalist');
    cy.intercept({ method: 'GET', url: '**/instances/*/*/data/*/validate', times: 1 }, [
      {
        severity: 1,
        field: 'SelectedItem',
        description: 'Duplicate error message',
      },
      {
        severity: 1,
        field: 'SelectedItemProfession',
        description: 'Duplicate error message',
      },
    ]);
    cy.get(appFrontend.nextButton).click();
    cy.get(appFrontend.errorReport)
      .should('be.inViewport')
      .should('contain.text', texts.errorReport)
      .should('contain.text', texts.next);
    cy.get(appFrontend.errorReport).find('li:contains("Duplicate error message")').should('have.length', 1);
  });
```

It intercepts the validation call that happens when you press the next button, and it finds and asserts that the error message is only displayed once. It looks like there are some problems with validation messages in the list component now, as the 'required fields' messages don't play well with the multiple data model bindings, and the component itself does not seem to render the validation messages at all (so if you have a full page of many components, it might be hard to find the list component in there).

Anyway, hope you find the example useful!

**Comment by johlie** [comment]
Is there anything I should do to fix it or is it hard to fix? The test fails. Everything works fine in our app where you get red writing under the table to see that you forgot to fill it out:
image

**Comment by olemartinorg** [comment]
The example test was meant as a starting point - I'm not sure it was designed to pass after this fix. You should adjust it to reproduce the problem this is supposed to fix, and then it should pass. 😊

**Comment by olemartinorg** [comment]
Tested manually now - works great! 🥳

**Pull request merged**
