### PR TITLE
Fix tab navigation for dropdown

### LINKED ISSUE #2486: TAB navigating through Dropdown component places the "focus" on weird places
### Description of the bug

In our app, we use up to three Dropdowns for selecting a country in a Repeating Group, one in the Repeating Group itself, two within Nested Repeating Groups within it. When tabbing through these and selecting a value for a Dropdown specifically, it behaves weirdly, especially the two in the Nested Repeating Groups (which seem to trigger TAB-navigation as if they were the one in the outer Repeating Group). 

If this description is unhelpful or confusing, see steps. 

The source code is in this app: https://altinn.studio/repos/brg/rrh-innrapportering
URL in TT02: https://brg.apps.tt02.altinn.no/brg/rrh-innrapportering/

### Steps To Reproduce

1. Open the app.
2. Login with foedselsnummer: 01812649198
3. Select organization ALLSLAGS ORIENTAL TIGER AS (311780352)
4. Select that the organization "Har reelle rettighetshavere".
5. Select "No" on "Har fødselsnummer/D-nummer".
6. Use TAB to navigate to "Bostedsland", select a country from the list using the keyboard only. 
7. Press enter.
8. Observe that the tab disappears, and if you press TAB now, you are at the very top of the document.
9. Fill out "Statsborgerskap" with any value. 
10. TAB back to "Bostedsland" (or TAB there from the top). Fill out any value and press enter. 
11. Observe that the TAB navigation now takes you to Statsborgerskap as expected. 
12. Select "Ja" on "Har posisjon eierskap", select 25.01%, select "Indirekte" on grunnlag.
13. Select "Ja" on "Er utenlandsk virksomhet?"
14. TAB to Land, select any value. 
15. Observe that you're now placed in Statsborgerskap above (this also happens with mouse navigation, the form jumps up to focus on Statsborgerskap). 
16. Select "Ja" on "Har posisjon kontroll...?", select 50%, select "Indirekte" on grunnlag. 
17. Do steps 13-15 here. 
18. Observe the same odd behavior. 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Magnusrm**
## Description

This PR removes the use of a dynamic key prop that was introduced to solve clearing the dropdown when using dynamic options and the source value for the options has changed. This does no longer seem to fix the previous issue.

Removing this workaround no longer causes the dropdown to completely re-render and lose focus after its value has updated.

## Related Issue(s)

- closes #2486 

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [x] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [x] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Review by olemartinorg — APPROVED** [review]
Looks good to me! :rocket:

**Review by bjosttveit — APPROVED** [review]
Good, since the workaround does not make a difference anymore it does not matter. The issue is clearing the dropdown text when the selected option value is cleared for being stale. The text will hang around even though the dropdown has no selected value. Have we filed an issue with the design system?

**Comment by Magnusrm** [comment]
@bjosttveit I have not filed a issue with DS. I can see to it 👍

**Comment by olemartinorg** [comment]
@Magnusrm @bjosttveit An issue already exists here: https://github.com/digdir/designsystemet/issues/2264

**Pull request merged**
