### PR TITLE
SummaryComponents display `You have not entered any information here` instead of nothing when no data is given for a field

### LINKED ISSUE #275: Design of empty optional fields in Summary
## Is your feature request related to a problem? Please describe
The design of the check-answer page looks confusing if a field is empty. We would like an indication that this field is empty.

## Describe the solution you'd like
An "empty"-tag where the text would be if the field were to be filled, and change the "Endre" text to "Legg til"

## Describe alternatives you've considered
None

## Additional context
This is how it is shown at the moment
image

How we would like it to look.
image

### PR DESCRIPTION
**Pull request by bjosttveit**
## Description

Shows `Du har ikke lagt inn informasjon her` / `You have not entered any information here` in summary components when no answer is given.

image

- [x] Make the text appear in italics to avoid confusion
- [x] Update texts after feedback from design
- [x] SingleInputSummary
- [x] MultipleChoiceSummary (reverts to singleInput when empty)
- [x] SummaryGroupComponent (both in case of no elements added and if a single field inside is empty)
- [x] AttachmentSummaryComponent
- [x] AttachmentWithTagSummaryComponent
- [x] MapComponentSummary (already had this functionality, but made some modifications)

## Related Issue(s)

- closes #275 

## Verification

- Manual testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added
  - [x] Cypress E2E test(s) have been added
  - [ ] No automatic tests are needed here
  - [ ] I want someone to help me make some tests
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been updated
  
  - [x] No changes/updates needed
- Changes/additions to component properties
  - [ ] Changes are reflected in both `src/layout/layout.d.ts` and `layout.schema.v1.json`, and these are all backwards-compatible
  - [x] No changes made
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board

### CODE REVIEW

**Review by olemartinorg — CHANGES_REQUESTED** [review]
Looks good so far! :rocket: Make sure you fix the tests that are failing now, and add some tests for this behavior. The way I see it, all the functionality we implement without automatic tests are things we are willing to lose in future refactoring. If I make a change later on that breaks this, we won't notice it during any test run, so by that definition it's not functionality we'd like to keep. So for this case, I disagree with your decision that 'no tests are needed here'. :wink:

**Comment by bjosttveit** [comment]
Understood, sir 🫡

**Review by olemartinorg — APPROVED** [review]
:1st_place_medal:

**Review by olemartinorg — APPROVED** [review]
Maybe the text should be in italics or something? :thinking: I think it looks deceptively much like something you've entered manually now.

**Comment by bjosttveit** [comment]
Yeah I thought of that too, totally agree, not sure exactly how to achieve that though. Would require some more changes, but is probably worth the wait.

**Pull request merged**
