### PR TITLE
Associate test and staging envs in pipeline

### PR DESCRIPTION
**Pull request by martinothamar**
## Description

Matching PR for https://github.com/Altinn/app-lib-dotnet/pull/881

## Related Issue(s)

- N/A

## Verification/QA

- Manual functionality testing
  - [ ] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [x] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [x] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Review by olemartinorg — COMMENTED** [review]
I'm not sure this leads to any practical difference for app-frontend. When we release, we build using `webpack.config.production.js`, which has its mode hard-coded to production, and doesn't seem to care about environment variables at all. And if it did, what should be different for a 'staging' build? Included source-maps, non-minimized code, or something else?

**Comment by martinothamar** [comment]
This is not about the build quality at all, but how we track release cadence and other things in the form of DORA metrics. The Swarmia tool we (maybe) will be using to track DORA metrics will track releases to test, staging and prod across all Altinn products, so we agreed that the mapping from preview and RC releases to these respective environments would be the most fitting

**Comment by olemartinorg** [comment]
I see! :thinking: It might not map exactly to our release procedures, then. I see that lately we've been naming releases `rc`, and `preview`, but there's no naming conventions set in stone here. If possible, varying on the 'pre-release' checkbox in github might be a better approach. In other words, I can't think of any practical difference between our `rc` and `preview` releases other than their names.

**Comment by martinothamar** [comment]
That's been the process thus far, but that is likely going to change. We are working on an ADR for amongst other things the release process, and part of that is trying to communicate practical differences between RC, preview and stable. We have discussed something along these lines:
* Production - stable releases, these should be bugfree
* RC - these are candidates for a stable release, we consider the feature work for the minor release done and don't expect to make any breaking changes
* Preview - work in progress, anything can happen

The reason we wanted RC in the first place is to have a more stable/complete release which could possibly motivate more apps to adopt these versions, while still leaving us some room to stabilize and sanity-check before releasing fully.

**Review by olemartinorg — APPROVED** [review]

**Comment by bjosttveit** [comment]
I did not see this before merge, but I think this could break the release workflow for preview releases. I added the `prod` environment to the release workflow in https://github.com/Altinn/app-frontend-react/pull/2550 becuse the secrets needed for the `Azure login` step was added to the environment secrets for `prod`. I don't have access to check if secrets have been added for other environments but I would assume it has not

**Pull request merged**
