### PR TITLE
bash script for purging front door cache

### PR DESCRIPTION
**Pull request by tjololo**
## Description
Script to purge cache in azure front door. This needs to be integrated with the release script so that when new minor/patch versions are released the CDN cache is purged for the update major/minor folder

Releated to issue https://github.com/Altinn/altinn-studio/issues/7566

## Related Issue(s)

- closes #{issue number}

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [x] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Comment by bjosttveit** [comment]
@tjololo Does this also need to be included in v3?

**Review by olemartinorg — APPROVED** [review]
Looks good to me! 💪 Will you integrate it into `release.sh` or should I? Also wondering the same as Bjørnar is wondering above.

**Comment by tjololo** [comment]
> @tjololo Does this also need to be included in v3?

Yes, as we will need to invalidate cache for v3 releases also it should be present in the v3 branch as well

**Comment by tjololo** [comment]
> Looks good to me! 💪 Will you integrate it into `release.sh` or should I? Also wondering the same as Bjørnar is wondering above.

I can have a go at integrating it into release.sh

**Comment by olemartinorg** [comment]
Great! 🙌 We can cherry-pick this to v3 after it is merged.

**Pull request merged**
