### PR TITLE
Validation failed to account for hidden groups

### PR DESCRIPTION
**Pull request by olemartinorg**
## Description
The validation procedure for empty fields failed to account for hidden groups.

## Fixes
- altinn/altinn-studio/issues/6398

## Verification
- [X] **Your** code builds clean without any errors or warnings
- [X] Manual testing done (required)
- [X] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [X] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)
- [x] Changelog is updated with a separate linked PR
  - [x] [altinn-app-frontend](https://docs.altinn.studio/community/changelog/app-frontend/)- (if applicable)
  - [ ] [nuget-packages](https://docs.altinn.studio/community/changelog/app-nuget/) - (if applicable)

### CODE REVIEW

**Comment by olemartinorg** [comment]
I'm submitting this as draft in order to run E2E tests which hopefully helps me detect if this has any adverse effects on other group types (most importantly repeating groups), although my manual testing made this change seem harmless.

I also have to triage other linked/duplicate issues.

**Comment by olemartinorg** [comment]
The somewhat similar [#7478](https://github.com/Altinn/altinn-studio/issues/7478) is not affected by this change, and requires a fix of its own. Opening this PR for review.

**Review by lorang92 — APPROVED** [review]
Neat! 💹 

Bump pacakge.json and I think we are good to go.

**Comment by olemartinorg** [comment]
@lorang92 To (hopefully) clear up the confusion: #7478 seems to be caused by re-using the `children` list in a group for more than just the component IDs (specifically when using `multiPage`). The validation logic doesn't include code to handle the concept of `children` being a list of `pageNum:componentID`, it just assumes that `children` is the normal list of `componentID`.

I'm still figuring out how best to solve that (I wish the validation code had as few branches as possible to handle these kinds of special cases), but I'm also finding other problems with `multiPage` where I would have assumed I'd see validation errors (but they're not being triggered).

**Pull request merged**
