### PR TITLE
Implement design system button into repeating groups

### PR DESCRIPTION
**Pull request by Magnusrm**
Changes the MUI IconButtons in repeating groups to buttons from the design system. 

## Description
- Changed delete and edit button into design-system buttons.
- Updated design-system buttons used in WrappedButton component, PrintButton component and DeletePopover component

## Related Issue(s)
- #439 

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

### CODE REVIEW

**Comment by bjosttveit** [comment]
After clicking edit, there is not enough room to show the text `Lagre og lukk`, so it wraps the text which does not look great.

image

**Comment by Magnusrm** [comment]
@bjosttveit Hmm.. this does not happen for me on any screen size 🤔 . Which browser are you using?

**Comment by bjosttveit** [comment]
> @bjosttveit Hmm.. this does not happen for me on any screen size 🤔 . Which browser are you using?

Firefox

**Comment by bjosttveit** [comment]
Not really related to this PR specifically, but rather the design system buttons. They are quite large considering this is the `small` variant.

image

Firefox shows the computed fontsize as `18px`, and looking at the figma-design, the small variant had a font-size of `16px` there. The icons also look a bit too large to me relative to the container.

**Review by bjosttveit — APPROVED** [review]
Code looks good! Great job 🥇 

Just take a look at the other comments 👍  Maybe the css of the design system buttons should be tweaked a little bit, but I'm not a designer 🤷

**Comment by StianVestli** [comment]
Har testet denne det knappene ser bra ut i repgruppen, men knappene inne i selve gruppen er fortsatt de samme, det er kanskje tenkt at det skal være slik? 
image

**Comment by Magnusrm** [comment]
@StianVestli 'Lagre og åpne neste' og 'Lagre og lukk' er også oppdatert med den nye versjonen av designsystem knappen. De ser fortsatt like ut ettersom den nye knappen også støtter disse utseendene og designet på repeterende grupper tilsier at de skal se slik ut. Så det er tiltenkt ja 😄

**Comment by StianVestli** [comment]
Betyr det at jeg kan styre utsende på knappene? eller er utsende fastsatt av repgruppe designet?

**Comment by Magnusrm** [comment]
Man kan ikke styre utseende på knappene per nå gjennom layout. Det stemmer at de er fastsatt av repgruppe komponenten.

**Pull request merged**
