### PR TITLE
Re-adding skipped tests

### PR DESCRIPTION
**Pull request by olemartinorg**
## Description

This also fixes our pre-commit hook so that it works on mac. This should prevent future accidents where tests are skipped.

## Related Issue(s)

- closes #{issue number}

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [x] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Review by cammiida — COMMENTED** [review]
Nice! Men lurer bare på om vi noen ganger faktisk vil skippe noen tester. Feks når en tast er flaky eller slikt. Blir det ikke litt dumt om vi ikke får lov til å commite om vi har skippa den da?

Går det eventuelt an å få warnings som man må eksplisitt trykke vekk i stedet? Og går det an å få det på push i stedet for commit? Så man få holde på "i fred" lokalt, men må følge standarder når man pusher til remote 😄

**Comment by olemartinorg** [comment]
Det går fint an å skippe tester med `it.skip()`, men jeg har til nå aldri sett et gyldig case hvor vi trenger å sjekke inn "skip alle andre enn denne testen" med `it.only()`. Tenker vi kan krysse den brua når vi kommer dit - eventuelt bare gjøre det eksplisitt da ved å faktisk legge til `it.skip()` på alle tester som skal skippes.

**Comment by cammiida** [comment]
Ah, ja my bad, det er jo to forskjellige greier 😅 only tror jeg går fint ja! 

Jeg pleier å bruke stash og commit litt om hverandre, men dette skal jeg tåle hehe 🙈

**Review by cammiida — APPROVED** [review]
🚀

**Pull request merged**
