### PR TITLE
fix: sort options based on their value not text resource key

### LINKED ISSUE #1634: Bug where sortOrder sorts based on textResource id and not value
When sorting selection components with `sortOrder`, the components are sorted by the `textResourceBinding.id`, and not by the actual value of the `textResource`.

Also, there seems to be an issue with language not being updated when switching between languages.

https://github.com/Altinn/app-frontend-react/assets/700139/cced6a00-c7fb-4a67-9f5c-7e7726ff9501

### PR DESCRIPTION
**Pull request by mikaelrss**
## Description

Fixes an issue where `sortOrder` on selection components would sort the options according to their text resource key if this was specified. 

## Related Issue(s)

- closes #1634 

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [x] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Comment by lassopicasso** [comment]
Looks good, but I tried testing locally to trigger the Percy error page. It works fine for me as well; however, I encountered a bug when switching languages back and forth. It seems to work the first time, but then it gets stuck in English.

https://github.com/Altinn/app-frontend-react/assets/74791975/05717da8-4f36-4b60-a436-39691dd81e37

**Comment by mikaelrss** [comment]
Yeah, nice spot! It seem like the language selector is broken on the `main` branch as well. I think this bug is there for all component types, not just the option components. You can see that the title for "Nytt fornavn" also changes to english, but won't change back. There exists an issue for this here: https://github.com/Altinn/app-frontend-react/issues/1632

**Review by lassopicasso — APPROVED** [review]
Aha I see ☺️ Approved then  👍

**Comment by mikaelrss** [comment]
I ran the tests again, and the precy screenshot with the error page disappeared. I am unsure what caused it in the first place, and I haven't been able to reproduce it locally.

**Pull request merged**
