### PR TITLE
Prettier: 120 character printWidth

### PR DESCRIPTION
**Pull request by olemartinorg**
## Description
As discussed on Slack, setting the printWidth to 120 characters. This PR includes a one-line change in prettier.config.js and a huge diff from `eslint --fix`.

## Related Issue(s)
- https://altinndevops.slack.com/archives/CDU1S3NLW/p1661331887029039

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

### CODE REVIEW

**Comment by olemartinorg** [comment]
@bjosttveit @Magnusrm What do you think? 80 character limit or 120 character limit? Yay or nay? If you regularly work on tiny laptop screens, the 120 character limit might be annoying when doing code review (but I guess that also depends on your vision).

**Comment by Magnusrm** [comment]
> @bjosttveit @Magnusrm What do you think? 80 character limit or 120 character limit? Yay or nay? If you regularly work on tiny laptop screens, the 120 character limit might be annoying when doing code review (but I guess that also depends on your vision).

120 chars is fine for me 👍

**Comment by bjosttveit** [comment]
> @bjosttveit @Magnusrm What do you think? 80 character limit or 120 character limit? Yay or nay? If you regularly work on tiny laptop screens, the 120 character limit might be annoying when doing code review (but I guess that also depends on your vision).

Could you make it 1200 characters? 🤣

image

**Comment by bjosttveit** [comment]
In all seriousness, 120 is nice, the 80-character limit has been kind of annoying.

**Comment by olemartinorg** [comment]
No proper tech workplace without sharing memes from The Office @bjosttveit! :partying_face: :joy:

I'll wait until #622 is merged so that we know this change won't actually affect anything (as the cypress tests are failing right now for everyone).

**Comment by olemartinorg** [comment]
I'm merging this straight away, since it's a huge merge conflict waiting to happen anyway. If you get a merge conflict from this change, resolving it is luckily very easy - just hit 'accept mine' and do nothing more. `eslint --fix` runs on your code when you commit, so it will re-do the changes for you automatically.

**Pull request merged**
