### PR TITLE
Add custom required validation text

### LINKED ISSUE #295: Flexible validation text for standard required field
### Description

Jeg testet dette med "shortName" nå for litt egendefinert tekst for obligatoriske felt. Jeg skjønte til slutt at jeg måtte legge det inni **textResourceBindings**-elementet (som var logisk selvfølgelig), men jeg ble skuffet over resultatet: 
image

Jeg skulle gjerne sett at jeg stod helt fritt til å velge hele valideringsteksten, altså at jeg slapp å få "Du må fylle ut" først. "Du må fylle ut" gir jo bare mening for tekstbokser/tallfelt, mens det for radioknapper f.eks. vil det være naturlig å bruke noe annet som "Du må velge minst ett alternativ" eller "Spørsmålet må besvares". I mitt tilfelle med kun en avkrysningsboks gir det heller ikke noen mening med en standard tekst av typen "Du må huke av for minst én tekstboks". Jeg tror dere ser poenget her...

### Additional Information

We would like to have an element f.ex. called "**validationText**" where we can choose the text freely. This option should also be available in **Altinn Studio** as a dropdown list so it's easy to refer to the defined texts.

Forslag til navn: requiredValidation

### PR DESCRIPTION
**Pull request by Magnusrm**
## Adding a new customisable validation text for `required` validations

Added a new property, `requiredValidation`, to `textResourceBindings`, which changes the displayed validation text to be the value of properties specified text resource. If this new text resource binding is used, the old default required message is not used.
 

## Related Issue(s)

- closes #295 

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [x] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [x] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [ ] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Changes/additions to component properties
  - [x] Changes are reflected in both `src/layout/layout.d.ts` and `layout.schema.v1.json`, and these are all backwards-compatible
  - [ ] No changes made
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [ ] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Review by olemartinorg — COMMENTED** [review]
I don't think this works with the `missingFieldsInLayoutValidations()` function, and neither the `validateEmptyFieldsListComponent()` function. Also, I would assume it conflicts with #1281, so coordinate that with @bjosttveit.

**Comment by bjosttveit** [comment]
Yes, almost any changes to `validation.ts` at this point will conflict with #1281, as most of the functions and related tests are deleted. Should be straightforward to implement afterwards though.

**Comment by Magnusrm** [comment]
@bjosttveit I'll hold off on this PR until your validation refactor is completed then, and solve the merge conflict then 👍

**Comment by Magnusrm** [comment]
Closed due to weird merge conflict resolution. New PR: https://github.com/Altinn/app-frontend-react/pull/1333

**Pull request closed without merging**
