### PR TITLE
Fix title in repeating group summary with reference to datamodel

### PR DESCRIPTION
**Pull request by bjosttveit**
## Related Issue(s)

- https://altinn.slack.com/archives/C02EJ9HKQA3/p1709903064872859

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [ ] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [ ] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [ ] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Review by olemartinorg — APPROVED** [review]
Looks good! I'm looking into some flaky tests, so I'll check the failing ones here to make sure I get these fixed as well. :raised_hands:

**Comment by EirikOlavHaugenSSB** [comment]
As far as I understood this has been fixed now, but it seems I still have the same issue described in the "related issues".
I can open a new bug report on it myself if there's more information needed.
https://altinn.slack.com/archives/C02EJ9HKQA3/p1709903064872859

**Comment by bjosttveit** [comment]
> I can open a new bug report on it myself if there's more information needed.

Please do

**Comment by EirikOlavHaugenSSB** [comment]
> > I can open a new bug report on it myself if there's more information needed.
> 
> Please do

A little difficult to explain in words, but hopefully the supplied screenshots illustrate the issue. 
https://github.com/Altinn/app-frontend-react/issues/2034

**Pull request merged**
