### PR TITLE
Remove footer feature flag

### PR DESCRIPTION
**Pull request by bjosttveit**
## Description

Assuming v4 requires app-lib version >= 7.6.0, we can remove the featureflag check for footer.

## Related Issue(s)

- https://github.com/Altinn/app-lib-dotnet/pull/183

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [x] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Comment by bjosttveit** [comment]
> And save 2 lines of code? 🤔 I'm not quite sure of the benefit of this. And as long as we don't have any other checks to make sure the backend version is supported, I'm not sure we should just pull out all the stops.

I thought we had agreed to have a minimum supported backend version?

**Comment by olemartinorg** [comment]
Possibly (I can't recall specifics), but I think we should implement some kind of sanity check in that case, and warn app developers in the frontend immediately if their backends are not updated.

And I also believe the feature flags from backend were supposed to be just that; flags that could be turned off. Although I guess for this specific feature it just guards against us calling an API endpoint that didn't exist in previous versions. So, what happens after this change - will older app-backends produce the 'unknown error' if the footer request fails? In that case, I agree that removing the feature flag check is a good thing.

**Comment by bjosttveit** [comment]
> And I also believe the feature flags from backend were supposed to be just that; flags that could be turned off. Although I guess for this specific feature it just guards against us calling an API endpoint that didn't exist in previous versions.

Yes this one is hardcoded to `true` only to prevent old apps from getting 404 (as opposed to 204) in their logs.

> will older app-backends produce the 'unknown error' if the footer request fails?

Not unless we also disable the `treat 404 as ok` logic for footer as well, which we could very well do

**Comment by olemartinorg** [comment]
> Not unless we also remove the treat 404 as ok logic for the footer as well, which we could very well do

Yep, do it! 🙌 Old backend = fatal error. That's much better than old backend = multiple fixed bugs/issues creeping back to the surface.

**Review by olemartinorg — APPROVED** [review]
Sorry, though I had approved it! 🚀

**Pull request merged**
