### PR TITLE
Use resolved node in summary switch

### LINKED ISSUE #747: Dynamic expressions in repeating groups are incorrect on summary-page
### Description of the bug

When having dynamic expressions for readonly on fields in repeating groups, the correct value of the dynamic expression is not shown on the summary page

### Steps To Reproduce

1. Clone the repository https://altinn.studio/repos/krt/krt-1230a-1/src/commit/58eaa73f7bf6a06d74fa49205213af1b0eba4c89
2. Start the app and log in as Sophie Salt
3. Fill in all required fields*. When filling out the repeating group do: 
- On the first group, select "Ja" on point "4.1 Har forsikringsforetaket et norsk organisasjonsnummer?", and use a valid orgnr (e.g. 974 760 673) on "4.2 Organisasjonsnummer". Fill in the rest of the group.
- Open a second group and select "Nei" on "4.1 Har forsikringsforetaket et norsk organisasjonsnummer?". Fill in the rest of the group. 
4. Go to the summary page and see that the "Edit"-buttons on the second group is on the wrong fields.

*To fill out the form faster, select "Nei" on "6.1 Behandler agentforetaket klientmidler?" and use valid email-adresses (e.g epost@epost.no)

### Additional Information

The readonly-state of the green fields on the form-page are not expressed by the "Endre"-buttons on the summary-page

Form-page:
image

Summary-page:
image

### PR DESCRIPTION
**Pull request by bjosttveit**
## Description

Fixes so that readonly correctly resolves for repeating group summary.

Tested in `krt-1230a-1` and everything resolves correctly now:

Screenshot 2023-03-03 at 08 57 00

## Related Issue(s)

- closes #747 

## Verification/QA

- Manual functionality testing
  - [x] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [?] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [x] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [x] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Changes/additions to component properties
  - [ ] Changes are reflected in both `src/layout/layout.d.ts` and `layout.schema.v1.json`, and these are all backwards-compatible
  - [x] No changes made
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [x] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [x] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [x] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

### CODE REVIEW

**Review by olemartinorg — APPROVED** [review]
Looks good!

**Comment by olemartinorg** [comment]
A little late, but I would have loved to have cypress tests that asserts this functionality. @bjosttveit Did you test in `frontend-test` and/or did you find a way to reproduce it there? Having tests for this would be nice, especially when I'm working on some larger refactoring in Summary at the moment.

**Comment by bjosttveit** [comment]
I only tested in the app linked in the issue, I dont think frontend test has any cases for dynamic read-only, but that could probably be tested by using the interceptLayout thing?

**Comment by olemartinorg** [comment]
Ah, never mind then. I don't think we should have to go into such detail to create separate tests to show that expressions work everywhere. Very soon the code will just transparently handle expressions everywhere anyway.

**Pull request merged**
